# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16wbDebjRNtHpEreT4HybQMwYWMziJlrS
"""

import streamlit as st
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing.image import img_to_array
import numpy as np
from PIL import Image

# Load model
model = load_model("face_emotion_vgg16.h5")
emotion_labels = ['Angry', 'Disgust', 'Fear', 'Happy', 'Neutral', 'Sad', 'Surprise']

# Preprocessing function
def preprocess_image(image):
    image = image.convert('L')  # Grayscale
    image = image.resize((48, 48))
    img_array = img_to_array(image)
    img_array = np.expand_dims(img_array, axis=0)
    img_array /= 255.0
    return img_array

# UI
st.title("Deteksi Emosi Wajah")
uploaded_file = st.file_uploader("Upload Gambar Wajah", type=["jpg", "png", "jpeg"])

if uploaded_file is not None:
    image = Image.open(uploaded_file)
    st.image(image, caption="Gambar Diupload", use_column_width=True)

    # Preprocess dan prediksi
    processed = preprocess_image(image)
    prediction = model.predict(processed)
    emotion = emotion_labels[np.argmax(prediction)]

    st.subheader("Prediksi Emosi:")
    st.success(emotion)